routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'ChatController@index')->name('home');
    Route::prefix('chat')->group(function () {
        Route::get('/create', 'ChatController@create')->name('chat.create');
        Route::get('/edit/{id}', 'ChatController@edit')->name('chat.edit');
        Route::post('/store', 'ChatController@store')->name('chat.store');  
        Route::get('/{id}', 'ChatController@view')->name('chat.view');
    });
    Route::prefix('message')->group(function () {
    	Route::post('/store', 'MessageController@store')->name('message.store');
    	Route::get('/delete/{id}', 'MessageController@delete')->name('message.delete');
    });
});

app/Chat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Chat extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_admin_id', 'title', 
    ];

    public function users()
    {
        return $this->belongsToMany('App\User','chat_participants', 'chat_id', 'user_id')->withTimestamps();
    }

    public function admin_chat()
    {
        return $this->belongsTo('App\User', 'user_admin_id', 'id');
    }

    public static function getUsersChat($id)
    {
        return Chat::find($id)->users->modelKeys();
    } 

    public static function checkAccessByAdminChat($id)
    {
        return Chat::where("id", $id)->where("user_admin_id", Auth::id())->first();
    }

    public static function getCountUnreadMessageByUser()
    {
        $user = Auth::user();
        $chats = Chat::all();
        $countUnreadMessage = [];
        foreach($chats as $chat){
            if ($user->can('view', $chat)) {
                $userInChat = ChatParticipant::getUserInChat($chat['id'], $user['id']);
                $countUnreadMessage[$chat['id']] = UnreadMessage::where('chat_participant_id', $userInChat['id'])->count();
                }
        }
        return $countUnreadMessage;
    }

}

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Message extends Model
{
    protected $fillable = [
        'author_id', 'content', 
    ];

    public function unreadMessage()
    {
        return $this->belongsToMany('App\ChatParticipant','unread_messages', 'message_id', 'chat_participant_id')->withTimestamps();
    }

    public function author_message()
    {
        return $this->belongsTo('App\ChatParticipant', 'author_id', 'id');
    }

    public static function getAllChatMessages($id)
    { 
        $messages = Message::whereIn('author_id', ChatParticipant::where('chat_id', $id)->pluck('id')->toArray())->withCount('unreadMessage')->get();
        return $messages;
    }

    public static function deleteMessage($id)
    {
        $message = Message::find($id);
        $message->unreadMessage()->detach();
        $message->delete();
        return true;
    }

}

app/Http/Controllers/ChatController.php
<?php

namespace App\Http\Controllers;

use App\{User, Chat, ChatParticipant, Message};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\StoreChatRequest;


class ChatController extends Controller
{    
    public function index()
    {
        $chats = Chat::all();
        $countUnreadMessage = Chat::getCountUnreadMessageByUser();
        return view(
            'home', 
            [
                "chats" => $chats,
                "countUnreadMessage" => $countUnreadMessage
            ]);
    }

    public function create()
    {
        $user = Auth::user();
        if ($user->can('create', Chat::class)) {
            $users = User::getAllNotUserAdminChat();
            return view('chat.create',["users" => $users]);
        } else {
            return redirect()->route("home");
        }
    }

    public function edit($id)
    {
        $user = Auth::user();
        $chat = Chat::find($id);
        if(empty($chat)){
            return redirect()->route('home')->withErrors(["Chat doesn't exists"]);
        }
        if ($user->can('edit', $chat)) {
            return view(
                'chat.edit',
                [
                    "chat" => $chat,
                    "users" => User::getAllNotUserAdminChat(),
                    "selected_users" => Chat::getUsersChat($id)
                ]);
        } else {
            return redirect()->route("home");
        }
    }

    public function store(StoreChatRequest $request)
    {
        $chat = Chat::updateOrCreate(
            ['id' => $request->id, 'user_admin_id' => Auth::id()],
            ['title' => $request['title']]
        );
        $chat->users()->sync(array_merge([$chat->user_admin_id], $request['participants_id']));
        return redirect()->route('home')->with(
            'message',
            "Chat #" . $chat->id . " \"" . $chat->title . "\" was saved!"
        );
    }

    public function view($id)
    {
        $user = Auth::user();
        $chat = Chat::find($id);
        $userInChat = ChatParticipant::getUserInChat($id, $user['id']);
        if ($user->can('view', $chat)) {
            $messages = Message::getAllChatMessages($id);
            $messages->each(function ($message) use ($userInChat){
                $message->unreadMessage()->detach($userInChat->id);
            });
            return view(
                'chat.view',
                [
                    "chat" => $chat,
                    "messages" => $messages
                ]);
        } else {
            return redirect()->route("home");
        }
    }

}

resources/views/chat/create.blade.php
@extends('adminlte::page')

@section('title', 'Messenger')

@section('content_header')
  <h1>Create Chat</h1>
@stop

@section('content')
  @if(session()->has('message'))
    <div class="alert alert-success">
      {{ session()->get('message') }}
    </div>
  @endif
  <div class="card">
    <div class="card-header">
       <h3 class="card-title">You can create chat here</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <form action="{{ route('chat.store') }}" enctype="multipart/form-data" method="post">
        {{ csrf_field() }}

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <div class="input-group-text">
              Chat Title
            </div>
          </div>
          <input type="text" name="title" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" value="{{ old('title') }}" placeholder="" autofocus>
          @if ($errors->has('title'))
            <div class="invalid-feedback">
              <strong>{{ $errors->first('title') }}</strong>
            </div>
          @endif
        </div>
                
        <div class="form-group">
          <label>Participants</label>
          <select name="participants_id[]" id="participant_id" class="select2" multiple="multiple" class="form-control {{ $errors->has('participants_id') ? 'is-invalid' : '' }}" data-placeholder="Select Participants" style="width: 100%;">
            @foreach($users as $user)
              <option value="{{$user->id}}" @if(old('participants_id') === $user->id) selected @endif>{{$user->name}}</option>
            @endforeach
          </select>
        </div>
        @if ($errors->has('participants_id'))
          <div class="invalid-feedback">
            <strong>{{ $errors->first('participants_id') }}</strong>
          </div>
        @endif

        <button type="submit" class="btn btn-primary btn-block btn-flat">
          Save  
        </button>
      </form>        
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
      $(function () {
      //Initialize Select2 Elements
      $('.select2').select2()
    })
    </script>
@stop

resources/views/chat/edit.blade.php
@extends('adminlte::page')

@section('title', 'Messenger')

@section('content_header')
  <h1>Edit Chat</h1>
@stop

@section('content')
  @if(session()->has('message'))
    <div class="alert alert-success">
      {{ session()->get('message') }}
    </div>
  @endif
  <div class="card">
    <div class="card-header">
       <h3 class="card-title">You can edit chat here</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <form action="{{ route('chat.store') }}" enctype="multipart/form-data" method="post">
        {{ csrf_field() }}

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <div class="input-group-text">
              Chat Title
            </div>
          </div>
          <input type="text" name="title" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" value="{{ old('title') ?? $chat['title']}}" placeholder="" autofocus>
          @if ($errors->has('title'))
            <div class="invalid-feedback">
              <strong>{{ $errors->first('title') }}</strong>
            </div>
          @endif
        </div>
        
        <div class="form-group">
          <label>Participants</label>
          <select name="participants_id[]" id="participants_id" class="select2" multiple="multiple" class="form-control {{ $errors->has('participants_id') ? 'is-invalid' : '' }}" data-placeholder="Select Participants" style="width: 100%;">
            @foreach($users as $user)
              <option value="{{$user->id}}" @if((!empty(old('participants_id')) && in_array($user->id, old('participants_id'))) || (empty(old('participants_id')) && in_array($user->id, $selected_users))) selected @endif>
                {{$user->name}}
              </option>
            @endforeach
          </select>
        </div>

        @if ($errors->has('participants_id'))
          <div class="invalid-feedback">
            <strong>{{ $errors->first('participants_id') }}</strong>
          </div>
        @endif

        <button type="submit" class="btn btn-primary btn-block btn-flat">
          Save  
        </button>
        <input type="hidden" name="id" value="{{ $chat->id }}">
      </form>        
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
      $(function () {
      //Initialize Select2 Elements
      $('.select2').select2()
    })
    </script>
@stop

resources/views/chat/view.blade.php
@extends('adminlte::page')

@section('title', 'Messenger')

@section('content_header')
@stop

@section('content')
  <div class="card direct-chat direct-chat-primary">
    <div class="card-header">
      <h3 class="card-title">{{$chat->title}}</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body h-100">
      <!-- Conversations are loaded here -->
      <div class="direct-chat-messages">
        @foreach($messages as $message)
        @if(Auth::id() !== $message->author_message->user->id)
        <!-- Message. Default to the left -->
        <div class="direct-chat-msg">
          <div class="direct-chat-infos clearfix">
            <span class="direct-chat-name float-left">{{$message->author_message->user->name}}</span>
            <span class="direct-chat-timestamp float-right">{{$message->updated_at}}</span>
          </div>
          <!-- /.direct-chat-infos -->
          <div class="direct-chat-text">
            {{$message->content}}
          </div>
          <!-- /.direct-chat-text -->
        </div>
        @elseif(Auth::id() == $message->author_message->user->id)
        <!-- /.direct-chat-msg -->
        <!-- Message to the right -->
        <div class="direct-chat-msg right">
          <div class="direct-chat-infos clearfix">
            <span class="direct-chat-name float-right">
              <div class="btn-group btn-group-sm align-self-center">
                <a onclick="editMessage({{$message['id']}})" class="btn btn-info"><i class="fas fa-pencil-alt"></i></a>
                <a href="{{ route('message.delete', ['id' => $message['id']]) }}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
              </div>
            </span>
            <span class="direct-chat-timestamp float-left">
              {{$message->updated_at}}
              @if($message->unread_message_count == 0)<i class="fas fa-check-double"></i>
              @elseif($message->unread_message_count !== 0)<i class="fas fa-check"></i>
              @endif
            </span>
          </div>
          <!-- /.direct-chat-infos -->
          <div class="direct-chat-text" id="message_{{$message['id']}}">
            {{$message->content}}
          </div>
        </div>
          <!-- /.direct-chat-text -->
        <!-- /.direct-chat-msg -->
        @endif
        @endforeach
      </div>
      <!--/.direct-chat-messages-->
    </div>
    <!-- /.card-body -->
  
    <div class="card-footer">
      <form action="{{ route('message.store') }}" enctype="multipart/form-data" method="post">
        {{ csrf_field() }}

        <div class="input-group">
          <input type="text" name="message" id="message_input" placeholder="Type Message ..." class="form-control {{ $errors->has('message') ? 'is-invalid' : '' }}" value="">
          @if ($errors->has('message'))
            <div class="invalid-feedback">
              <strong>{{ $errors->first('message') }}</strong>
            </div>
          @endif
          <span class="input-group-append">
            <button type="submit" class="btn btn-primary">Send</button>
          </span>
          <input type="hidden" name="chat_id" value="{{ $chat->id }}">
          <input type="hidden" name="id" id="message_edit_id" value="">
        </div>
      </form>
    </div>
    <!-- /.card-footer-->
  </div>
  <!--/.direct-chat -->

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
      function editMessage(messageId)
        {
          let message = $("#message_"+messageId).html();
          $("#message_input").val(message);
          $("#message_edit_id").val(messageId);
        }
    </script>
@stop